"""Galileo falling-body thought experiment for Gaia v0.5."""

from gaia.engine.lang import claim, contradict, derive, equal, note

context = note(
    "This package models Galileo's falling-body thought experiment as a "
    "comparison between two explanatory models. It does not treat vacuum "
    "falling as an observed fact inside the package."
)

thought_experiment_setup = note(
    "In the tied-body thought experiment, a heavy body and a light body are "
    "bound together and considered as one composite system."
)

vacuum_setup = note(
    "The vacuum case is a counterfactual setup in which the resisting medium is absent."
)

daily_observation = claim(
    "In air, heavy bodies are often observed to fall faster than light bodies."
)

aristotle_model = claim(
    "Model A: weight itself causes heavier bodies to have greater natural falling speed."
)

medium_model = claim(
    "Model B: differences in falling speed in air are caused by resistance from the medium."
)

aristotle_daily_prediction = derive(
    "Under Model A, heavy bodies should fall faster than light bodies in air.",
    given=[aristotle_model],
    rationale=(
        "If weight directly increases natural falling speed, then heavier bodies "
        "falling faster in air is expected."
    ),
    label="aristotle_daily_observation_path",
)

aristotle_daily_match = equal(
    aristotle_daily_prediction,
    daily_observation,
    rationale=(
        "The daily falling-body observation matches the prediction generated by the "
        "weight-speed model."
    ),
    label="aristotle_daily_match",
)

medium_daily_prediction = derive(
    "Under Model B, heavy bodies can fall faster than light bodies in air.",
    given=[medium_model],
    rationale=(
        "If air resistance creates the observed speed differences, then heavier compact "
        "bodies can fall faster in air without weight itself setting the natural speed."
    ),
    label="medium_daily_observation_path",
)

medium_daily_match = equal(
    medium_daily_prediction,
    daily_observation,
    rationale=(
        "The daily falling-body observation matches the prediction generated by the "
        "medium-resistance model."
    ),
    label="medium_daily_match",
)

composite_faster = derive(
    "The tied composite should fall faster than the heavy body alone.",
    given=[aristotle_model],
    background=[thought_experiment_setup],
    rationale=(
        "Under the weight-speed model, greater total weight implies greater natural "
        "falling speed. In the tied-body setup, the composite contains the heavy body "
        "plus an additional light body, so it is heavier than the heavy body alone."
    ),
    label="aristotle_composite_faster",
)

composite_slower = derive(
    "The tied composite should fall slower than the heavy body alone.",
    given=[aristotle_model],
    background=[thought_experiment_setup],
    rationale=(
        "Under the same weight-speed model, the slower light body should retard the "
        "faster heavy body when the two are tied together."
    ),
    label="aristotle_composite_slower",
)

aristotle_paradox = contradict(
    composite_faster,
    composite_slower,
    rationale=(
        "For the same tied composite, the weight-speed model yields incompatible predictions."
    ),
    label="aristotle_paradox",
)

vacuum_equal_fall_prediction = derive(
    "In vacuum, bodies of different weights fall at the same rate.",
    given=[medium_model],
    background=[vacuum_setup],
    rationale=(
        "If observed speed differences come from medium resistance, then in the vacuum "
        "setup, where the resisting medium is absent by definition, the source of those "
        "differences is absent."
    ),
    label="medium_vacuum_equal_fall_prediction",
)

__all__ = [
    "aristotle_daily_match",
    "aristotle_daily_prediction",
    "aristotle_model",
    "aristotle_paradox",
    "composite_faster",
    "composite_slower",
    "daily_observation",
    "medium_daily_match",
    "medium_daily_prediction",
    "medium_model",
    "vacuum_equal_fall_prediction",
]

# Re-export the CLI-authored ``authored/`` submodule so statements added
# via ``gaia author`` compose into this hand-authored package. Empty by
# default — the hand-authored DSL above is the package's Tier-1 canon.
from . import authored as _authored  # noqa: E402
from .authored import *  # noqa: E402, F403

__all__ = [*__all__, *_authored.__all__]
